#!/usr/bin/env bash

set -x

mkdir -p cellranger_tiny/fastqs
cp -r /opt/cellranger-2.0.0/cellranger-tiny-fastq/1.2.0/* ./fastqs

cd cellranger_tinyfastqs
gunzip *.fastq.gz



cd cellranger_tiny

cp /opt/cellranger_tiny/*  ./

